csi:
  disk:
    enabled: false
    controller:
      enabled: true
  nas:
    enabled: false
    controller:
      enabled: true
  oss:
    enabled: false
    controller:
      enabled: true
  local:
    enabled: false
    controller:
      enabled: true
  bmcpfs:
    enabled: true
    controller:
      enabled: true
